# -*- coding: utf-8 -*-
"""Codigo_Rutas_de_Acoso_Medellin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UJUlbgI-qK-7eJoCoH8kVvA6nkelkQWC

### Importacion de los Datos
"""

import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TRABAJO EDA/calles_de_medellin_con_acoso.csv',sep =';')

df.head()

print(df.shape)
df.info() #identificar valores faltantes y tipo de obj
df.describe() #resumen est de aquellas var numericas

"""### Forma 2"""

# Commented out IPython magic to ensure Python compatibility.
!pip install geopandas

# %matplotlib inline
import matplotlib.pyplot as plt
import geopandas as gpd
import pysal as ps
from pysal.contrib.viz import mapping as maps

import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
from shapely import wkt

#load data
edges = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TRABAJO EDA/calles_de_medellin_con_acoso.csv',sep=';')
edges['geometry'] = edges['geometry'].apply(wkt.loads)
edges = gpd.GeoDataFrame(edges)

area = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TRABAJO EDA/calles_de_medellin_con_acoso.csv',sep=';')
area['geometry'] = area['geometry'].apply(wkt.loads)
area = gpd.GeoDataFrame(area)

#Create plot
fig, ax = plt.subplots(figsize=(12,8))

# Plot the footprint
area.plot(ax=ax, facecolor='black')

# Plot street edges
edges.plot(ax=ax, linewidth=1, edgecolor='dimgray')

plt.tight_layout()

